# File: digicert_connector.py
# Copyright (c) 2021 Splunk Inc.
#
# Licensed under Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.txt)
#

PLATFORM_MAP = {
    "Apache": 2,
    "Barracuda": 41,
    "Bea Weblogic 7 and older": 29,
    "BEA Weblogic 8 & 9": 42,
    "Cisco": 30,
    "Citrix (Other)": 39,
    "Citrix Access Essentials": 46,
    "Citrix Access Gateway 4.x": 50,
    "Citrix Access Gateway 5.x and higher": 58,
    "cPanel": 43,
    "F5 Big-IP": 31,
    "F5 FirePass": 32,
    "IBM HTTP Server": 7,
    "Java Web Server (Javasoft / Sun)": 10,
    "Juniper": 33,
    "Lighttpd": 44,
    "Lotus Domino": 11,
    "Mac OS X Server": 49,
    "Microsoft Exchange Server 2003": 47,
    "Microsoft Exchange Server 2007": 36,
    "Microsoft Exchange Server 2010": 48,
    "Microsoft Exchange Server 2013": 68,
    "Microsoft Exchange Server 2016": 71,
    "Microsoft Forefront Unified Access Gateway": 66,
    "Microsoft IIS 1.x to 4.x": 13,
    "Microsoft IIS 10": 70,
    "Microsoft IIS 5 or 6": 14,
    "Microsoft IIS 7": 40,
    "Microsoft IIS 8": 67,
    "Microsoft Live Communications Server 2005": 37,
    "Microsoft Lync Server 2010": 59,
    "Microsoft Lync Server 2013": 69,
    "Microsoft OCS R2": 60,
    "Microsoft Office Communications Server 2007": 38,
    "Microsoft Small Business Server 2008 & 2011": 62,
    "Netscape Enterprise Server": 15,
    "Netscape iPlanet": 9,
    "nginx": 45,
    "Novell iChain": 65,
    "Novell NetWare": 17,
    "Oracle": 18,
    "Qmail": 34,
    "SunOne": 35,
    "Tomcat": 24,
    "WebStar": 26,
    "Zeus Web Server": 28,
    "Other": -1
}
