GOOGLE_CONTACTS_SCOPE = 'https://www.googleapis.com/auth/contacts'
GOOGLE_OTHER_CONTACTS_SCOPE_READ_ONLY = 'https://www.googleapis.com/auth/contacts.other.readonly'
GOOGLE_DIRECTORY_SCPOPE_READ_ONLY = 'https://www.googleapis.com/auth/directory.readonly'
GOOGLE_PROFILE_SCOPE = 'https://www.googleapis.com/auth/userinfo.profile'
OTHER_CONTACTS_RESOURCE_NAME_PREFIX = 'otherContacts/'
