# Copyright (c) 2020 Splunk Inc.
#
# Licensed under Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.txt)
#
TANIUM_DETECT_DEFAULT_LIMIT = 100
TANIUM_DETECT_MAX_LIMIT = 500
TANIUM_DETECT_API_BASE_URL = '/plugin/products/detect3/api/v1'
TANIUM_DETECT_API_PATH_SUPPRESSION_RULES = '/suppression-rules'
TANIUM_DETECT_API_PATH_SOURCES = '/sources'
TANIUM_DETECT_API_PATH_SOURCE_TYPES = '/source-types'
TANIUM_DETECT_API_PATH_NOTIFICATIONS = '/notifications'
TANIUM_DETECT_API_PATH_LABELS = '/labels'
TANIUM_DETECT_API_PATH_INTELS = '/intels'
TANIUM_DETECT_API_PATH_ALERTS_COUNTS = '/alerts/counts'
TANIUM_DETECT_API_PATH_ALERTS_COUNT = '/alerts/count'
TANIUM_DETECT_API_PATH_ALERTS = '/alerts'
TANIUM_DETECT_API_PATH_AUTH = '/auth'
TANIUM_DETECT_TIMEZONE = 'timezone'
TANIUM_DETECT_HOUR_GAP = 3600
