VSOC_TICKET_KEY = 'id'
VSOC_TICKET_ARTIFACT_LABEL = 'vsoc_ticket'
VSOC_WORKLOG_ENTRY_ARTIFACT_LABEL = 'vsoc_worklog_entry'
VSOC_WORKLOG_ENTRY_DEFAULT_TYPE = 'CUSTOMER'
VSOC_TICKETS_ENDPOINT = '/Ticket'
VSOC_TICKET_ENDPOINT = '/Ticket/{id}'
VSOC_BACKFILL_DAYS = 7
