version: "3.2"

services:
  app_tester:
    image: repo.splunk.com/splunk/infra/phantom_apps_tester:${IMAGE_TAG:-latest}
    environment:
      BUILD_USER_ID: ${USER:-localbuild}
      TEST_BRANCH: ${TEST_BRANCH:-master}
      WORKSPACE: /builds/phantom-apps
    volumes:
    - .:/builds/phantom-apps/${APP_REPO_NAME}
    command: sleep 28800
    secrets:
    - app_artf_token
    - app_deploy_key
    - gitlab_api_token

secrets:
  app_artf_token:
    file: ~/.docker/secrets/app_artf_token
  app_deploy_key:
    file: ~/.docker/secrets/app_deploy_key
  gitlab_api_token:
    file: ~/.docker/secrets/gitlab_api_token
